# Generated by Django 4.1.7 on 2023-02-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=40)),
                ('task', models.TextField()),
                ('deadline', models.DateField()),
                ('is_submitted', models.BooleanField(default=False)),
            ],
        ),
    ]
