# Generated by Django 4.1.7 on 2023-03-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=40, unique=True)),
                ('task', models.TextField()),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('homework_id', models.IntegerField()),
                ('is_done', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
