# Generated by Django 4.1.7 on 2023-02-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('homework_id', models.IntegerField()),
                ('is_done', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='homework',
            name='is_submitted',
        ),
    ]
