# Generated by Django 4.1.7 on 2023-02-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_alter_homework_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomework',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
