# Generated by Django 4.1.7 on 2023-03-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_alter_homework_id_alter_homework_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomework',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
